### ISSUE TITLE
wrong deb package

### ISSUE THREAD

**Issue by Ygarr** [adolfintel/NoteBot#1]
Debian system
Setting up notebot (1.5-1) ...
cp: cannot create regular file '/autostart/': Not a directory
dpkg: error processing package notebot (--configure):
 installed notebot package post-installation script subprocess returned error exit status 1
 Errors were encountered while processing:
 notebot.

While remove:
 package is in a very bad inconsistent state; you should
 reinstall it before attempting a removal
Errors were encountered while processing:
 notebot

**Comment by adolfintel** [comment]
Sorry about the issue.
The file is supposed to go to $XDG_CONFIG_DIRS/autostart/Notebot.desktop
Is that variable empty on your system? Or did they change something again?
